# dashboard/app.py

import json
import os
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd
import streamlit as st

# -------------------------------------------------------------------
# Project root & imports
# -------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PIPELINE_SCRIPT = PROJECT_ROOT / "scripts" / "run_pipeline.py"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from explainability.genai_explainer import generate_explanation

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------

DATA_DIR = PROJECT_ROOT / "data" / "processed"
FEATURES_PATH = DATA_DIR / "features.parquet"
METRICS_PATH = DATA_DIR / "metrics.json"

# -------------------------------------------------------------------
# Streamlit setup
# -------------------------------------------------------------------

st.set_page_config(
    page_title="Telemetry Intelligence Platform",
    layout="wide",
)

st.title("Telemetry Intelligence Platform")
st.caption("Cloud telemetry analytics with deterministic rules and responsible ML")

# -------------------------------------------------------------------
# Helper: run pipeline
# -------------------------------------------------------------------

def run_pipeline():
    return subprocess.run(
        [sys.executable, str(PIPELINE_SCRIPT)],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=True,
    )

# -------------------------------------------------------------------
# First-run handling
# -------------------------------------------------------------------

if not FEATURES_PATH.exists():
    st.error("Processed telemetry not found.")

    st.markdown(
        """
        This dashboard depends on outputs generated by the analytics pipeline.
        No processed data was detected in the workspace.
        """
    )

    st.code("python scripts/run_pipeline.py")

    if st.button("Run Pipeline", type="primary"):
        with st.spinner("Running pipeline…"):
            try:
                result = run_pipeline()
                st.success("Pipeline completed successfully.")
                st.text_area("Pipeline Output", result.stdout, height=250)
                time.sleep(1)
                st.experimental_rerun()
            except subprocess.CalledProcessError as exc:
                st.error("Pipeline execution failed.")
                st.text_area("Error Output", exc.stderr, height=250)

    st.stop()

# -------------------------------------------------------------------
# Load data
# -------------------------------------------------------------------

df = pd.read_parquet(FEATURES_PATH)

metrics = None
if METRICS_PATH.exists():
    with open(METRICS_PATH, "r") as f:
        metrics = json.load(f)

# -------------------------------------------------------------------
# Overview
# -------------------------------------------------------------------

st.subheader("Overview")

col1, col2 = st.columns(2)
with col1:
    st.metric("Total Events", len(df))
with col2:
    high_risk_pct = round(df["label_high_risk"].mean() * 100, 2)
    st.metric("High-Risk Events (%)", high_risk_pct)

# -------------------------------------------------------------------
# Distribution
# -------------------------------------------------------------------

st.subheader("Risk Distribution")
st.bar_chart(df["label_high_risk"].value_counts())

# -------------------------------------------------------------------
# Pipeline metrics
# -------------------------------------------------------------------

if metrics:
    st.subheader("Pipeline Metrics")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Invalid Events Dropped", metrics["ingestion"]["invalid_events"])
    with col2:
        st.metric(
            "Baseline Positive Rate",
            round(metrics["baseline"]["positive_rate"], 3),
        )
    with col3:
        st.metric(
            "Unsupervised Anomaly Rate",
            round(metrics["unsupervised"]["anomaly_rate"], 3),
        )

# -------------------------------------------------------------------
# Explainability (STRICTLY FACT-BASED)
# -------------------------------------------------------------------

st.subheader("AI-Generated Summary")

high_risk_count = int(df["label_high_risk"].sum())
total_events = len(df)
high_risk_pct = round((high_risk_count / total_events) * 100, 2)

summary_payload = {
    "total_events": total_events,
    "high_risk_count": high_risk_count,
    "high_risk_percentage": high_risk_pct,
}

if os.getenv("GOOGLE_API_KEY"):
    st.caption(
        "GenAI explanations are enabled via `GOOGLE_API_KEY`. "
        "No automated decisions or enforcement are performed."
    )
else:
    st.caption(
        "GenAI explanations are disabled (no `GOOGLE_API_KEY`). "
        "A deterministic fallback summary is shown."
    )

genai_text = None
if metrics and metrics.get("genai_summary"):
    genai_text = metrics["genai_summary"]
else:
    genai_text = generate_explanation(summary_payload)

st.info(genai_text)
