# dashboard/app.py

import json
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd
import streamlit as st

# -------------------------------------------------------------------
# Project root & imports
# -------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PIPELINE_SCRIPT = PROJECT_ROOT / "scripts" / "run_pipeline.py"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from explainability.genai_explainer import generate_explanation

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------

DATA_DIR = PROJECT_ROOT / "data" / "processed"
FEATURES_PATH = DATA_DIR / "features.parquet"
METRICS_PATH = DATA_DIR / "metrics.json"

# -------------------------------------------------------------------
# Streamlit setup
# -------------------------------------------------------------------

st.set_page_config(
    page_title="Telemetry Intelligence Platform",
    layout="wide",
)

st.title("Telemetry Intelligence Platform")
st.caption("Cloud telemetry analytics with deterministic rules and responsible ML")

# -------------------------------------------------------------------
# Helper: run pipeline
# -------------------------------------------------------------------

def run_pipeline():
    """Run the end-to-end pipeline as a subprocess."""
    return subprocess.run(
        [sys.executable, str(PIPELINE_SCRIPT)],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=True,
    )

# -------------------------------------------------------------------
# First-run / missing data handling
# -------------------------------------------------------------------

if not FEATURES_PATH.exists():
    st.error("Processed telemetry not found.")

    st.markdown(
        """
        This dashboard depends on outputs generated by the analytics pipeline.
        No processed data was detected in the workspace.
        """
    )

    st.markdown("### Available Actions")
    st.code("python scripts/run_pipeline.py")

    if st.button("Run Pipeline", type="primary"):
        with st.spinner("Running pipeline… This may take a moment."):
            try:
                result = run_pipeline()
                st.success("Pipeline completed successfully.")

                st.subheader("Pipeline Output")
                st.text_area(
                    label="stdout",
                    value=result.stdout,
                    height=250,
                )

                # Give filesystem a moment to settle, then reload UI
                time.sleep(1)
                st.experimental_rerun()

            except subprocess.CalledProcessError as exc:
                st.error("Pipeline execution failed.")

                st.subheader("Error Output")
                st.text_area(
                    label="stderr",
                    value=exc.stderr,
                    height=250,
                )

    st.stop()

# -------------------------------------------------------------------
# Load data
# -------------------------------------------------------------------

df = pd.read_parquet(FEATURES_PATH)

metrics = None
if METRICS_PATH.exists():
    with open(METRICS_PATH, "r") as f:
        metrics = json.load(f)

# -------------------------------------------------------------------
# Overview
# -------------------------------------------------------------------

st.subheader("Overview")

col1, col2 = st.columns(2)
with col1:
    st.metric("Total Events", len(df))
with col2:
    st.metric(
        "High-Risk Events (%)",
        round(df["label_high_risk"].mean() * 100, 2),
    )

# -------------------------------------------------------------------
# Distribution
# -------------------------------------------------------------------

st.subheader("Risk Distribution")
st.bar_chart(df["label_high_risk"].value_counts())

# -------------------------------------------------------------------
# Pipeline metrics
# -------------------------------------------------------------------

if metrics:
    st.subheader("Pipeline Metrics")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Invalid Events Dropped",
            metrics["ingestion"]["invalid_events"],
        )

    with col2:
        st.metric(
            "Baseline Positive Rate",
            round(metrics["baseline"]["positive_rate"], 3),
        )

    with col3:
        st.metric(
            "Unsupervised Anomaly Rate",
            round(metrics["unsupervised"]["anomaly_rate"], 3),
        )

    # Supervised status
    supervised_metrics = metrics.get("supervised", {})
    if isinstance(supervised_metrics, dict) and "warning" in supervised_metrics:
        st.warning(
            f"Supervised ML skipped: {supervised_metrics['warning']}"
        )

# -------------------------------------------------------------------
# Explainability
# -------------------------------------------------------------------

st.subheader("AI-Generated Summary")

summary_text = f"""
Total events analyzed: {len(df)}
High-risk proportion: {df['label_high_risk'].mean():.2f}
"""

st.caption(
    "Explainability output is currently a placeholder. "
    "No automated decisions or enforcement are performed."
)

st.info(generate_explanation(summary_text))
